import type { ServiceKeywordProfile } from '../../locale-formatting';

export const SEWAGE_KEYWORDS: Record<string, ServiceKeywordProfile> = {
    'sewer-cleaning': {
        slug: 'sewer-cleaning',
        synonyms: ['تسليك صرف', 'فتح مجاري', 'تسليك بالوعات', 'تسليك مواسير'],
        primaryKeyword: 'شركة تسليك مجاري {city}',
        metaTitle: 'تسليك مجاري {city} — فتح انسداد فوري + كمبروسر + سلك + 24 ساعة من {price} ريال 2026',
        metaDescription: 'تسليك مجاري {city} ✓ فتح فوري ✓ كمبروسر ✓ سلك ✓ طوارئ 24 ساعة ✓ بدون تكسير. قارن {count}+ شركة تسليك {city}.',
        h1: 'تسليك مجاري {city} — فتح انسداد فوري بالكمبروسر 24 ساعة 2026',
        secondaryKeywords: [
            'تسليك مجاري {city}',
            'فتح مجاري {city}',
            'تسليك صرف {city}',
            'شركة تسليك {city}',
            'تسليك بالوعات {city}',
        ],
        longTailKeywords: [
            'تسليك مجاري {city} طوارئ',
            'تسليك مجاري {city} بالكمبروسر',
            'تسليك مجاري {city} حي {neighborhood}',
        ],
        topQuestions: [
            'كم سعر تسليك المجاري {city}؟',
            'ما أسباب انسداد المجاري؟',
            'هل يوجد تسليك مجاري طوارئ {city}؟',
            'ما الفرق بين التسليك بالسلك والكمبروسر؟',
        ],
        cityPrefixPattern: 'ba',
        usp: 'فتح فوري + 24 ساعة + كمبروسر',
    },
    'sewage-pumping': {
        slug: 'sewage-pumping',
        synonyms: ['شفط مجاري', 'تنظيف بيارات', 'شفط صرف صحي', 'سحب بيارات', 'شفط حفرة امتصاصية', 'تفريغ بيارة'],
        primaryKeyword: 'شركة شفط بيارات {city}',
        metaTitle: 'شفط بيارات {city} — وايت 10 و 20 طن من {price} ريال + خدمة 24 ساعة 2026',
        metaDescription: 'وايت شفط بيارات {city} ✓ 10 و 20 طن ✓ طوارئ 24 ساعة ✓ أسعار ثابتة ✓ تنظيف بيارة. قارن {count}+ وايت شفط {city}.',
        h1: 'شفط وتنظيف بيارات {city} — وايتات بجميع الأحجام 2026',
        secondaryKeywords: ['شفط بيارات {city}', 'وايت شفط {city}', 'شفط مجاري {city}', 'تنظيف بيارات {city}', 'تفريغ بيارة {city}', 'شفط حفرة امتصاصية {city}'],
        longTailKeywords: ['شفط بيارات {city} رخيص', 'وايت شفط {city} حي {neighborhood}', 'شفط بيارات {city} طوارئ', 'شفط بيارة 20 طن {city}'],
        topQuestions: ['كم سعر شفط البيارة {city}؟', 'كم حجم وايت الشفط المتوفر؟', 'هل يوجد شفط بيارات طوارئ 24 ساعة {city}؟', 'كم مرة تحتاج البيارة شفط في السنة؟'],
        cityPrefixPattern: 'ba',
        usp: 'وايتات 10 و 20 طن + طوارئ 24 ساعة',
    },
    'sewer-suction-trucks': {
        slug: 'sewer-suction-trucks',
        synonyms: ['وايت صرف', 'سيارة شفط', 'تنكر شفط', 'لوري شفط', 'وايت صرف صحي', 'وايت بيارات'],
        primaryKeyword: 'وايت شفط {city}',
        metaTitle: 'وايت شفط صرف صحي {city} — 10 و 20 طن بأسعار ثابتة من {price} ريال 2026',
        metaDescription: 'وايت شفط {city} ✓ 10 طن ✓ 20 طن ✓ طوارئ 24 ساعة ✓ أسعار ثابتة ✓ تفريغ مرخص. يصل لجميع الأحياء. قارن {count}+ وايت {city}.',
        h1: 'وايت شفط صرف صحي {city} — جميع الأحجام بأسعار ثابتة 2026',
        secondaryKeywords: ['وايت شفط {city}', 'سيارة شفط {city}', 'وايت صرف {city}', 'تنكر شفط {city}', 'وايت بيارات {city}', 'لوري شفط {city}'],
        longTailKeywords: ['وايت شفط {city} رخيص', 'وايت شفط {city} حي {neighborhood}', 'وايت شفط 20 طن {city}', 'وايت شفط طوارئ ليلي {city}'],
        topQuestions: ['كم سعر وايت الشفط {city}؟', 'ما أحجام وايتات الشفط المتوفرة؟', 'هل الوايت يوصل لجميع أحياء {cityName}؟', 'هل يوجد وايت شفط طوارئ ليلي {city}؟'],
        cityPrefixPattern: 'ba',
        usp: '10 و 20 طن + أسعار ثابتة + تفريغ مرخص',
    },
    'sewage-compressor': {
        slug: 'sewage-compressor',
        synonyms: ['كمبروسر تسليك', 'كمبروسر مجاري', 'ضغط مجاري', 'تسليك بالضغط العالي', 'كمبروسر انسداد'],
        primaryKeyword: 'كمبروسر مجاري {city}',
        metaTitle: 'كمبروسر تسليك مجاري {city} — ضغط عالي + فتح فوري بدون تكسير 2026',
        metaDescription: 'كمبروسر مجاري {city} ✓ ضغط عالي ✓ فتح انسداد فوري ✓ بدون تكسير ✓ خدمة طوارئ. لأصعب الانسدادات. قارن {count}+ شركة {city}.',
        h1: 'كمبروسر تسليك مجاري {city} — ضغط عالي بدون تكسير 2026',
        secondaryKeywords: ['كمبروسر مجاري {city}', 'كمبروسر تسليك {city}', 'تسليك بالضغط {city}', 'كمبروسر انسداد {city}', 'ضغط مجاري {city}', 'فتح انسداد بالكمبروسر {city}'],
        longTailKeywords: ['كمبروسر مجاري {city} رخيص', 'كمبروسر {city} حي {neighborhood}', 'تسليك مجاري بالضغط العالي {city}', 'كمبروسر مجاري طوارئ {city}'],
        topQuestions: ['كم سعر الكمبروسر {city}؟', 'هل الكمبروسر يحل الانسداد الصعب؟', 'ما الفرق بين الكمبروسر والسلك في التسليك؟', 'هل الكمبروسر يتلف المواسير؟'],
        cityPrefixPattern: 'ba',
        usp: 'ضغط عالي + بدون تكسير + طوارئ',
    },
    'sewage-suction': {
        slug: 'sewage-suction',
        synonyms: ['شفط بيارات', 'وايت شفط', 'شفط صرف', 'تفريغ بيارة'],
        primaryKeyword: 'شفط بيارات {city}',
        metaTitle: 'شفط بيارات {city} — وايت 10 و 20 طن + طوارئ 24 ساعة 2026',
        metaDescription: 'شفط بيارات {city} ✓ وايت 10 و 20 طن ✓ طوارئ 24 ساعة ✓ أسعار ثابتة. قارن {count}+ وايت شفط {city}.',
        h1: 'شفط بيارات {city} — وايتات بجميع الأحجام 24 ساعة 2026',
        secondaryKeywords: ['شفط بيارات {city}', 'وايت شفط {city}', 'شفط صرف {city}'],
        longTailKeywords: ['شفط بيارات {city} رخيص', 'شفط بيارات طوارئ {city}'],
        topQuestions: ['كم سعر شفط البيارة {city}؟', 'هل يوجد شفط طوارئ 24 ساعة؟'],
        cityPrefixPattern: 'ba',
        usp: 'وايتات 10 و 20 طن + طوارئ',
    },
    'sewage-unblocking': {
        slug: 'sewage-unblocking',
        synonyms: ['تسليك مجاري', 'فتح انسداد', 'تسليك صرف', 'تسليك بالوعات'],
        primaryKeyword: 'تسليك مجاري {city}',
        metaTitle: 'تسليك مجاري {city} — فتح انسداد فوري + كمبروسر + 24 ساعة 2026',
        metaDescription: 'تسليك مجاري {city} ✓ فتح فوري ✓ كمبروسر ✓ سلك ✓ طوارئ 24 ساعة. قارن {count}+ شركة تسليك {city}.',
        h1: 'تسليك مجاري {city} — فتح انسداد فوري بالكمبروسر 2026',
        secondaryKeywords: ['تسليك مجاري {city}', 'فتح مجاري {city}', 'تسليك صرف {city}'],
        longTailKeywords: ['تسليك مجاري {city} طوارئ', 'تسليك مجاري {city} بالكمبروسر'],
        topQuestions: ['كم سعر تسليك المجاري {city}؟', 'ما أسباب انسداد المجاري؟'],
        cityPrefixPattern: 'ba',
        usp: 'فتح فوري + كمبروسر + طوارئ 24 ساعة',
    },
    'drain-cleaning': {
        slug: 'drain-cleaning',
        synonyms: ['تنظيف مجاري', 'غسيل مجاري', 'تنظيف صرف', 'تنظيف بالوعات'],
        primaryKeyword: 'تنظيف مجاري {city}',
        metaTitle: 'تنظيف مجاري {city} — غسيل بالضغط + تنظيف عميق + وقائي 2026',
        metaDescription: 'تنظيف مجاري {city} ✓ غسيل بالضغط ✓ تنظيف عميق ✓ وقائي ✓ منع الانسداد. قارن {count}+ شركة {city}.',
        h1: 'تنظيف مجاري {city} — غسيل بالضغط العالي لمنع الانسداد 2026',
        secondaryKeywords: ['تنظيف مجاري {city}', 'غسيل مجاري {city}', 'تنظيف صرف {city}'],
        longTailKeywords: ['تنظيف مجاري وقائي {city}', 'غسيل مجاري بالضغط {city}'],
        topQuestions: ['كم سعر تنظيف المجاري {city}؟', 'كم مرة تحتاج المجاري تنظيف؟'],
        cityPrefixPattern: 'ba',
        usp: 'غسيل بالضغط + تنظيف عميق + وقائي',
    },
    'tank-maintenance': {
        slug: 'tank-maintenance',
        synonyms: ['صيانة خزانات', 'إصلاح خزان', 'ترميم خزان', 'صيانة خزان مياه'],
        primaryKeyword: 'صيانة خزانات {city}',
        metaTitle: 'صيانة وإصلاح خزانات {city} — ترميم + عزل + تنظيف + ضمان 2026',
        metaDescription: 'صيانة خزانات {city} ✓ إصلاح ✓ ترميم ✓ عزل ✓ تنظيف ✓ ضمان. خزانات أرضية وعلوية. قارن {count}+ شركة {city}.',
        h1: 'صيانة وإصلاح خزانات المياه {city} — ترميم وعزل 2026',
        secondaryKeywords: ['صيانة خزانات {city}', 'إصلاح خزان {city}', 'ترميم خزان {city}'],
        longTailKeywords: ['صيانة خزان ارضي {city}', 'إصلاح تسريب خزان {city}'],
        topQuestions: ['كم سعر صيانة الخزان {city}؟', 'هل يمكن إصلاح الخزان بدون تغييره؟'],
        cityPrefixPattern: 'ba',
        usp: 'إصلاح + ترميم + عزل + ضمان',
    },
};

