import type { ServiceKeywordProfile } from '../../keyword-strategy';

export const MOVING_KEYWORDS: Record<string, ServiceKeywordProfile> = {
    'furniture-moving': {
        slug: 'furniture-moving',
        synonyms: ['نقل اثاث', 'نقل موبيليا', 'نقل عفش مع الفك والتركيب', 'شركة نقل'],
        primaryKeyword: 'شركة نقل عفش {city}',
        metaTitle: 'نقل عفش {city} — فك وتركيب + تغليف + ضمان من {price} ريال 2026',
        metaDescription: 'شركة نقل عفش {city} ✓ فك وتركيب ✓ تغليف ✓ ضمان شامل ✓ عمالة مدربة. قارن {count}+ شركة نقل اثاث معتمدة {city}.',
        h1: 'نقل عفش {city} — فك وتركيب وتغليف مع ضمان شامل 2026',
        secondaryKeywords: [
            'نقل عفش {city}',
            'نقل اثاث {city}',
            'ارخص نقل عفش {city}',
            'اسعار نقل العفش {city}',
            'شركات نقل العفش {city}',
            'افضل شركة نقل عفش {city}',
        ],
        longTailKeywords: [
            'شركة نقل عفش {city} رخيصه',
            'نقل عفش {city} مع الفك والتركيب',
            'دينا نقل عفش {city}',
            'نقل عفش {city} حي {neighborhood}',
            'افضل شركة نقل اثاث {city} مجربه',
            'نقل عفش {city} مع التغليف',
        ],
        topQuestions: [
            'كم سعر نقل العفش {city}؟',
            'ما افضل شركة نقل عفش {city}؟',
            'كيف اختار شركة نقل عفش موثوقة {city}؟',
            'هل يوجد نقل عفش رخيص {city}؟',
        ],
        cityPrefixPattern: 'ba',
        usp: 'فك وتركيب + تغليف + ضمان',
    },
    'furniture-storage': {
        slug: 'furniture-storage',
        synonyms: ['تخزين عفش', 'مستودعات تخزين', 'تخزين اغراض', 'مخازن اثاث'],
        primaryKeyword: 'شركة تخزين اثاث {city}',
        metaTitle: 'تخزين أثاث {city} — مستودعات مؤمنة + مراقبة 24/7 من {price} ريال/شهر 2026',
        metaDescription: 'تخزين اثاث {city} ✓ مستودعات مؤمنة ✓ مراقبة 24 ساعة ✓ تغليف ✓ تأمين. قارن {count}+ شركة تخزين عفش {city}.',
        h1: 'تخزين أثاث {city} — مستودعات مؤمنة بمراقبة شاملة 2026',
        secondaryKeywords: [
            'تخزين عفش {city}',
            'مستودعات تخزين {city}',
            'تخزين اغراض {city}',
            'ايجار مستودع {city}',
            'شركة تخزين {city}',
        ],
        longTailKeywords: [
            'تخزين اثاث {city} شهري',
            'مستودع تخزين مؤمن {city}',
            'تخزين عفش {city} رخيص',
            'مخازن اثاث {city} حي {neighborhood}',
        ],
        topQuestions: [
            'كم سعر تخزين الاثاث {city} شهرياً؟',
            'هل مستودعات التخزين {city} آمنة؟',
            'ما شروط تخزين العفش {city}؟',
            'هل يوجد تأمين على الاثاث المخزن؟',
        ],
        cityPrefixPattern: 'ba',
        usp: 'مستودعات مؤمنة + مراقبة 24/7',
    },
    'dyna': {
        slug: 'dyna',
        synonyms: ['دينا نقل', 'سيارة نقل', 'شاحنة نقل', 'دينات'],
        primaryKeyword: 'دينا نقل {city}',
        metaTitle: 'دينا نقل عفش {city} — 3 و5 و7 طن + أسعار ثابتة من {price} ريال 2026',
        metaDescription: 'دينا نقل {city} ✓ 3 و5 و7 طن ✓ نقل داخلي وخارجي ✓ أسعار ثابتة ✓ خدمة سريعة. قارن {count}+ دينا نقل {city}.',
        h1: 'دينا نقل عفش {city} — جميع الأحجام بأسعار ثابتة 2026',
        secondaryKeywords: [
            'دينا نقل عفش {city}',
            'دينا نقل اثاث {city}',
            'سيارة نقل {city}',
            'دينا {city}',
            'ارخص دينا نقل {city}',
        ],
        longTailKeywords: [
            'دينا نقل عفش {city} رخيصه',
            'دينا نقل {city} صغيره',
            'دينا نقل {city} حي {neighborhood}',
            'سعر دينا نقل {city}',
        ],
        topQuestions: [
            'كم سعر الدينا {city}؟',
            'ما أحجام الدينات المتوفرة {city}؟',
            'هل تتوفر دينا نقل صغيرة {city}؟',
            'كم تحمل دينا النقل من أثاث؟',
        ],
        cityPrefixPattern: 'ba',
        usp: 'أحجام متنوعة + أسعار ثابتة',
    },
    'moving-out': {
        slug: 'moving-out',
        synonyms: ['نقل اثاث بين المدن', 'نقل عفش خارج المدينة', 'نقل لمسافات طويلة'],
        primaryKeyword: 'نقل عفش بين المدن {city}',
        metaTitle: 'نقل عفش بين المدن من {cityName} — شحن آمن مع ضمان 2026',
        metaDescription: 'شركة نقل عفش بين المدن من {cityName} ✓ تغليف احترافي ✓ سيارات مغلقة ✓ ضمان شامل. قارن أسعار {count}+ شركة نقل اثاث بين المدن.',
        h1: 'نقل عفش بين المدن من {cityName} — شحن آمن 2026',
        secondaryKeywords: [
            'نقل عفش من {cityName}',
            'شركة نقل اثاث بين المدن {city}',
            'نقل عفش خارج {cityName}',
            'شحن اثاث من {cityName}',
        ],
        longTailKeywords: [
            'نقل عفش من {cityName} الى الرياض',
            'نقل عفش من {cityName} الى جدة',
            'شركة نقل عفش بين المدن رخيصة',
            'نقل اثاث مسافات طويلة {city}',
        ],
        topQuestions: [
            'كم سعر نقل العفش بين المدن من {cityName}؟',
            'كم يستغرق نقل العفش بين المدن؟',
            'هل يوجد ضمان على النقل بين المدن؟',
            'ما أفضل شركة نقل بين المدن؟',
        ],
        cityPrefixPattern: 'fi',
        usp: 'سيارات مغلقة + تأمين شامل',
    },
    'dabab': {
        slug: 'dabab',
        synonyms: ['دباب توصيل', 'نقل اغراض صغيرة', 'توصيل طلبات'],
        primaryKeyword: 'دباب نقل عفش {city}',
        metaTitle: 'دباب نقل {city} — توصيل سريع للأغراض الصغيرة بأسعار اقتصادية 2026',
        metaDescription: 'دباب نقل {city} ✓ توصيل سريع ✓ أغراض صغيرة ✓ أسعار اقتصادية ✓ يوصل لجميع الأحياء. اطلب دباب نقل {city} الآن.',
        h1: 'دباب نقل {city} — توصيل سريع واقتصادي للأغراض الصغيرة 2026',
        secondaryKeywords: [
            'دباب نقل {city}',
            'دباب توصيل {city}',
            'نقل اغراض صغيرة {city}',
        ],
        longTailKeywords: [
            'دباب نقل عفش {city} رخيص',
            'دباب نقل {city} حي {neighborhood}',
        ],
        topQuestions: [
            'كم سعر دباب النقل {city}؟',
            'هل يوجد دباب نقل عفش {city}؟',
        ],
        cityPrefixPattern: 'ba',
        usp: 'نقل سريع + أسعار اقتصادية',
    },
};
